name: mc_dashboard
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  bitsdojo_window: ^0.1.5
  visibility_detector: ^0.3.3
  pdf: ^3.6.0
  path_provider: ^2.0.11
  image: ^3.0.1 
  lucide_icons_flutter: ^2.0.1
  flutter_toastr: ^1.0.3
  fluttertoast: ^8.2.12
  clipboard: ^0.1.3
  lottie: ^2.6.0
  url_launcher: ^6.3.1
  excel: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/MC_logo.png
    - lib/json_files/equipos.json
    - lib/json_files/pass_rg.json
    - lib/json_files/pass_herramientas.json
    - lib/json_files/user.json
    - assets/lottie/agent_business.json
    - assets/lottie/download_animation.json
    - assets/lottie/check.json
    - assets/bd_local/BD_TEST.xlsx
    - assets/icons/MC_logo.ico


